populateItems("cardview-parent","Afforestation/ Reforestation","In this section, we are looking at the forest disturbances data recorded nearly run-time using satellite. Through the forest disturbances, we can deduce that the change in the structure and composition of the ecosystem which may lead to the initiative of afforestation. This is an interesting topic that you may want to delve into.", "https://search.earthdata.nasa.gov/search?p=C1597928934-NOAA_NCEI&m=-7.801055068926801!-25.734375!1!1!0!0%2C2&fs10=Afforestation/Reforestation&fsm0=Forest%20Science&fst0=Agriculture","../../../Images/afforestation-reforestation.jpg");

populateItems("cardview-parent","Forest Conservation","To understand forest conservation, you have to understand the conditions of the forest in the world. The data set provides you with the images obtained from a satellite in a sun-synchronous orbit. This will give you an overview about the forest conditions in Canada, hence providing a deeper insight about forest conservation.", "https://search.earthdata.nasa.gov/search?p=C1597928934-NOAA_NCEI&m=-7.801055068926801!-25.734375!1!1!0!0%2C2&fs10=Forest Conservation&fsm0=Forest%20Science&fst0=Agriculture","../../../Images/forest_conservation.jpg");

populateItems("cardview-parent","Forest Fire Science","We have always heard of forest fires in the news but do you really know what is it? To understand the forest fire better, we can have a look at the fire, smoke and radiation from biomass burning. This gives a clue about the forest fire. Other than that, we can look at the data regarding the emission of gases like carbon dioxide and sulfur dioxide produced during burning. The data can be obtained using satellites and hence analysing forest fires with deeper insight.", "https://search.earthdata.nasa.gov/search?p=C1597928934-NOAA_NCEI&m=-7.801055068926801!-25.734375!1!1!0!0%2C2&fs10=Forest Fire Science&fsm0=Forest%20Science&fst0=Agriculture","../../../Images/forest_fire_science.jpg");

populateItems("cardview-parent","Forest Harvesting And Engineering","Every year, forests are harvested for land and resources. However, These will affect the carbon cycle, hence the amount of carbon dioxide in the atmosphere. Other than that, forests should be harvested according to sets of rules. If you want to know more about these, you have to explore the data sets here!", "https://search.earthdata.nasa.gov/search?p=C1597928934-NOAA_NCEI&m=-7.801055068926801!-25.734375!1!1!0!0%2C2&fs10=Forest Harvesting And Engineering&fsm0=Forest%20Science&fst0=Agriculture","../../../Images/forest_harvesting_and_engineering.jpg");

populateItems("cardview-parent","Forest Management","Forests are treasures. Due to large harvest, the numbers of forests are decreasing greatly and we should learn how to manage the resources and preserve the forests. These are related to the habitats of the flora and fauna. If you want to know how to manage a forest, have a look at the data that provides great visualization about the forests!", "https://search.earthdata.nasa.gov/search?p=C1597928934-NOAA_NCEI&m=-7.801055068926801!-25.734375!1!1!0!0%2C2&fs10=Forest Management&fsm0=Forest%20Science&fst0=Agriculture","../../../Images/forest_management.jpg");

populateItems("cardview-parent","Forest Mensuration","Have you ever wondered how much a forest is worth? You can find the answer here! The data will provide you with all the information you need about the forest and its value!", "https://search.earthdata.nasa.gov/search?p=C1597928934-NOAA_NCEI&m=-7.801055068926801!-25.734375!1!1!0!0%2C2&fs10=Forest Mensuration&fsm0=Forest%20Science&fst0=Agriculture","../../../Images/forest_mensuration.jpg");

populateItems("cardview-parent","Forest Yields","Are you interested in learning the yields from forest? Have a look at the usage of the lands after clearing the forests! This will give you an idea about the value of the forest yields. Other than that, you can find all the resources obtained from the forests here too!", "https://search.earthdata.nasa.gov/search?p=C1597928934-NOAA_NCEI&m=-7.801055068926801!-25.734375!1!1!0!0%2C2&fs10=Forest Yields&fsm0=Forest%20Science&fst0=Agriculture","../../../Images/forest_yields.jpg");

populateItems("cardview-parent","Reforestation","Global warming is becoming a serious defect nowadays and forest resources are depleted due to human exploitation. It is vital to know about reforestation for conserving the resources. If you want to know the effect of reforestation on the environment, have a look at the data sets which provide relevant information on reforestation!", "https://search.earthdata.nasa.gov/search?p=C1597928934-NOAA_NCEI&m=-7.801055068926801!-25.734375!1!1!0!0%2C2&fs10=Reforestation&fsm0=Forest%20Science&fst0=Agriculture","../../../Images/reforestation.jpg");